nodeLinker: node-modules

packageExtensions:
  "@react-native/babel-plugin-codegen@*":
    peerDependencies:
      "@babel/core": "*"
  "babel-plugin-transform-flow-enums@*":
    peerDependencies:
      "@babel/core": "*"
  "babel-preset-expo@*":
    peerDependencies:
      "@babel/core": "*"
  "eslint-config-expo@*":
    peerDependencies:
      "typescript": "*"
  "eslint-plugin-expo@*":
    peerDependencies:
      "typescript": "*"
  "expo-linking@*":
    peerDependencies:
      "expo": "*"
  "expo@*":
    peerDependencies:
      "@babel/core": "*"
  "expo-router@*":
    peerDependencies:
      "react": "*"
      "react-native": "*"
  "react-native@*":
    peerDependencies:
      "@babel/core": "*"
