# Example EAS Workflow with GitHub Comment Job

name: Build and Comment on PR
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # build_ios:
  #   name: Build iOS app
  #   type: build
  #   params:
  #     platform: ios
  #     profile: development

  # build-android:
  #   name: Build Android app
  #   type: build
  #   params:
  #     platform: android
  #     profile: preview

  # publish_update:
  #   name: Publish update
  #   type: update
  #   params:
  #     branch: development
  #     message: "Update for PR #${{ github.event.pull_request.number }}"

  # post-comment:
  #   name: Post GitHub comment
  #   type: github-comment
  #   needs: [build-ios, build-android, publish-update]
  #   params:
  #     message: |
  #       🎉 Builds and updates are ready for testing!

  #       Please download the appropriate build for your device and scan the QR code to test the latest changes.
  #     builds:
  #       - ${{ after.build-ios.outputs.build_id }}
  #       - ${{ after.build-android.outputs.build_id }}
  #     updates:
  #       - ${{ after.publish-update.outputs.first_update_group_id }}
  post-comment:
    name: Post GitHub comment
    # needs: [build_ios, publish_update]
    type: github-comment
    params:
      message: |
        🎉 Builds and updates are ready for testing!

        Please download the appropriate build for your device and scan the QR code to test the latest changes.
      builds:
        # - ${{ after.build_ios.outputs.build_id }}
        - "0ec576a7-da6f-41d2-9901-3ab79cf56194"
      updates:
        # - ${{ after.publish_update.outputs.first_update_group_id }}
        - "812c66ca-5790-4105-9680-8620cc5daf4a"
