name: Github Comment

on:
  pull_request: {}

jobs:
  #   build_ios:
  #     name: Build iOS app
  #     type: build
  #     params:
  #       platform: ios
  #       profile: production
  #   deploy_web:
  #     type: deploy
  #     env:
  #       EXPO_DEBUG: "1"
  #       EXPO_LOCAL: "1"
  # params:
  #   alias: pr
  comment:
    type: github-comment
    # after: [build_ios, deploy_web]
    params:
      build_ids:
        - 019be482-4df9-791b-92c8-4a6c28453733
      deployment_ids:
        - 99x8l1ewjk
