name: Hello

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']
  schedule:
    - cron: '*/5 * * * *'

jobs:
  my_job:
    env:
      GITHUB_COMMIT_MESSAGE: ${{github.commit_message}}
    steps:
      - name: My first step
        run: echo "$GITHUB_COMMIT_MESSAGE"
  show_whats_next:
    type: doc
    needs: [my_job]
    params:
      md: This is a job to *test* eas-workflow
