name: Hello2

on:
  push:
    branches:
      - main

jobs:
  my_job:
    env:
      GITHUB_COMMIT_MESSAGE: ${{github.commit_message}}
    steps:
      - name: My first step
        run: echo "$COMMIT_MESSAGE"
      - name: My second step
        run: echo "${{github.commit_message}}"
  show_whats_next:
    type: doc
    needs: [my_job]
    params:
      md: This is a job to *test* eas-workflow
