on:
  push:
    branches: ['main']

jobs:
  build_ios:
    name: Build iOS app
    type: build
    params:
      platform: ios
      profile: production
  submit_ios:
    name: Submit to Apple App Store
    needs: [build_ios]
    type: testflight
    env:
      EXPO_DEBUG: 1
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      submit_beta_review: true
      internal_groups:
        - internal_without_auto_dist
      #  - internal_with_auto_dist
      #external_groups:
      #  - external
      #changelog: "This is a changelog"
